# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json
version: "1"

dev_mode: true

watch_config:
  enabled: true
  interval: "10s"
  startup_delay:
    enabled: false
    maximum: "10s"

log_level: "debug"

localhost_fallback_inside_docker: true
listen_addr: "0.0.0.0:3002" # Necessary because in Docker there is an automated fallback via 'host.docker.internal:host-gateway' to 0.0.0.0
graphql_path: "/graphql"
introspection:
  enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 10s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
playground:
  enabled: true
  path: "/" # For some fucked up reason you CANNOT give the playground a dedicated path, as this will prepend whichever path you chose to the fetching URL and results in errors
